### ISSUE TITLE
ruby version mismatch across .ruby-version and in Gemfile statement 

### ISSUE THREAD

**Issue by brarnaudovski** [CaravanTransit/Caravan-App#117]
## Detailed Description

When trying to make fresh `bundle install` , _bundler_ gives error:
```shell
Caravan-App (master) $ bundle 
Your Ruby version is 2.3.0, but your Gemfile specified 2.4.4
```
This is expected error from _bundler_ as the ruby version differs from .ruby-version file and the version specified in _Gemfile_ 
## Possible Implementation

I've already made the changes , but I am not able to make a PR (or at least it is not defined not to do it)
## Your Environment

Not relevant for this issue.
Just `git clone` and `bundle install` will give the error

**Comment by vkoves** [comment]
@brarnaudovski  - thanks for the issue! I believe the `.rubyversion` file was not added intentionally, since RVM can actually read the Ruby version from the `Gemfile`. Would it work for you if we just deleted the file? I can do that quite quickly, and might just push that through without a PR.

Also, you can make a PR by forking the repo. Learn more [at GitHub help](https://help.github.com/articles/fork-a-repo/), which explains how to propose changes to a project.

**Comment by brarnaudovski** [comment]
I suggest you leave it.
Creation of `.ruby-version` file and the `ruby` statement in `Gemfile` file is by default when building Rails apps, starting from Rails 5.2.0
[https://github.com/rails/rails/issues/30007](https://github.com/rails/rails/issues/30007)

My changes were not only on .ruby-version, but also in some of the wiki files that reverences ruby version as 2.3.0, in which case  it is wrong.

**Comment by vkoves** [comment]
@brarnaudovski thanks for the insight, that's a great point. I'd love to see a pull request for these changes, and I can review them quickly to get that fixed. Let me know if I can help you in any way in making a PR.
