### ISSUE TITLE
Should We Have Notifications?

### ISSUE THREAD

**Issue by robertbrentwilson** [CaravanTransit/Caravan-App#34]
Talk about what it would be like to have our application send notifications to users as they approach stops with current issues or concerns. This would encourage users to keep the app and to continue to be active in using it. If people can be notified in real time if there is an issue at a stop close to them it could certainly help keep people safe. 

Example: If someone reports violence at a stop, people coming in on the next train could know right away that they should be looking out for a potential threat or concern.

**Comment by AcademyInPeril** [comment]
We should probably get started thinking about what settings for notification levels we should have, and what the default notification settings are. We don't necessarily want to spam people with every issue reported near them, but having crime-related notifications enabled by default (at the very least) seems reasonable.

**Comment by mrupprecht17** [comment]
So having it be "close by" would also alert people who aren't necessarily inbound to the platform. That might be good in any case, since, in the case of crime, they get an alert about nearby crime, but I don't think someone who lives near the Western stop would want a notification every time someone reports something.

We could narrow it down 1. by checking if they're moving toward the stop (I imagine we could do this with location data that goes back something like 1 minute), or, if that's too intrusive or hard to do, 2. by checking if they've checked the app recently, specifically for that stop or one very close by.

Ultimately, I feel like notifications could be done, but I think we'd need some feedback from people to see if they'd be widely used enough.

**Comment by vkoves** [comment]
The functional spec specifies that we will have notifications, so I'm going to close this issue in light of #95
