### ISSUE TITLE
Should we move to React-Redux or another front-end framework?

### ISSUE THREAD

**Issue by vkoves** [CaravanTransit/Caravan-App#85]
This question was raised at Chi Hack Night, and I wanted to post it here to get feedback from developers. What are folks thoughts on moving to a front-end framework, potentially React-redux? Do folks feel like that would help us overall, and are there current contributors who have experience with React-redux?

**Comment by vkoves** [comment]
@usufruct, @laredotornado - I wanted to tag you two in this since you have made contributions to Caravan. What are your thoughts?

**Comment by usufruct** [comment]
hi @vkoves, thanks for bringing up the question. In no particular order here are some thoughts on the issue

IMHO we should adopt a JS framework. React (or Vue) are good choices if you are looking to build interactive components but don't necessarily need all the extensive features of something like Angular. React has a larger user base than Vue and larger dev team behind it. For better or worse Facebook supports the React project. I liked the getting started docs the React and Vue teams have put together.

I helped the SE org where I work settle on using React (Redux is optional) for new projects and also as the upgrade target for legacy projects using Angular 1.xx. We decided against upgrading Angular in part because front end development in Angular felt too much like 'Angular Developemnt'.

Just using JQuery and building out Javascript bits without the same sort of rigor as would be appliecd to Ruby code (tests, code structure), won't scale very well. I used to be a Frond End Dev, and IMHO frameworks like React help establish healthy developemnt patterns. A Framework like React helps direct JS coding to be well-tested and modular.

Personally I don't have a ton of day to day experience with React. Most of my efforts are have just been playing around with it in my free time. The Rails project I spend most of my time working on has a ton of leagacy Angular 1/Coffescript code (much of it untested :( ) that we haven't had the time to dig out from under in order to convert.

I would be curious what people think about *how* we use a framework like React. Do we start building a single page app, or do we continue to route the application in Rails and only use React to enhance the front end user experience where it makes sense?

Another question I have is whether people want to bring in something like Bootstrap or Semantic UI to help build out interactive elements? (Please forgive me if we already have something like that available that I missed.)

Last thing, [Create React App](https://github.com/facebook/create-react-app) is a great way to try out React.

**Comment by vkoves** [comment]
Thanks for the feedback @usufruct! I think making a single page app might make sense for Caravan, since we want to have mobile app functionality like push notifications and such that will require web workers anyway, and I think making Caravan a one page app would allow for some offline functionality. However, I'm by no means an expert on that aspect of things. However, I do wonder if there are benefits to preserving the Ruby on Rails routing, and only using React where we need it. On the other hand, that might make for a really fragmented codebase.

I am an Angular developer for my job, and I can definitely see your point around that making a project feel like Angular development, and that could definitely exclude folks. I also agree with your thoughts around just using bits of jQuery, as I've already had issues come up where I would like to see code tested but it isn't really simple without a larger JS framework around things.

We also don't have something like Bootstrap; I've been doing the CSS completely custom. I'm not opposed to it, and it's been suggested before. Especially since Caravan is meant to have a relatively large reach, it is probably best to start with something like that and customize it, since that will ensure a level of robustness to our styling that I don't know that we can guarantee ourselves.

**Comment by arieldiamond** [comment]
Hello, just catching up. I believe I was the one who proposed using React/Redux instead of rails views. I've been using react/redux in my job and I've never seen a framework more universally accepted in a profession where everyone has lots of competing opinions -- we have maybe 8 backend frameworks and two frontend frameworks (some react, some react+redux). I am personally not a fan of SPAs as linking to specific pages has a lot of value, but I could be convinced. In addition, I far, far prefer Redux over React without Redux, as Redux does an incredible job managing state. Both are superior to rails views in terms of speed and reactive updates. I'm not going to die on this hill, however. Caravan has rails views that work, and rewriting would set us back quite a bit.

**Comment by Semiroundpizza8** [comment]
The group agreed that we'd stick to ruby on rails as of right now, this issue should be closed 👍
